script:
- npm test
notifications:
  email:
  - cleverstack@github.com
  irc:
  - chat.freenode.net#cleverstack
language: node_js
node_js:
- '0.10'
- '0.11'
- '0.12'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
