script:
- npm test
notifications:
  email:
  - cleverstack@github.com
  irc:
  - chat.freenode.net#cleverstack
  hipchat:
    rooms:
      secure: l56KYS9GL3QeaBO5UaDUtWhIR05eVxMRXcDubTelf4EG4yk/aOc/+d6ChyNEeRTKLrulnzfZDUS4Mqa7RLUvvodkTV2dnR779pE+axMFnBwfWlOGjBxwF0reT0kAwtCm3w5aW7hd+bK72Nw/theRYBhXl8noxSPBrH+qVDUhdhs=
language: node_js
node_js:
- '0.10'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
