script:
  - "npm test"

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/7c4b5021376e475d1d47
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

language: node_js

node_js:
  - '0.10'
  - '0.11'
  - '0.12'
  - 'iojs'

branches:
  only:
    - master

cache:
  directories:
    - node_modules
